language: node_js
node_js:
  - '8'
env:
  global:
    # doubleface GITHUB_TOKEN
    # to generate yours : travis encrypt GITHUB_TOKEN=<your_GITHUB_TOKEN> -r konnectors/cozy-konnector-echeancier-maif
    - secure: "WqehZaig0ITje/iwv3LB8rXR0a58X0HHbz9Ot7xacJ3xFeDp/eMHgFDaWwHDpf+dYk8lG1cwvoGGRU3GQ6Vv11DbuI6jOq52/uTEP8hcxoNPaVj/QrLkJvs0bsNIvrBwEifqIJmD3ITfC/1P7vKnIaJP2k0fVxK8wEbK1BGzPNd5eK/lNdONED2ItdgXFtaP4f/I4lYYqnHDoemRP2WJhk9CgqiY6MYXi34nrBCqH6qvBLITF0NNFXUmniL0DpSe+iRORq6xnGIUAG+tvggjVIFsK0FlXASuSiBlakIfczsq9DGsHqydxUwBUadirvqbLaZ0L59aW96j9BizhT/RyERfDxZ9DiH1aKUKWvpdtpJzpmYjO5lsnsLaG7ZTs+I6bLjzwSGhD0BV+3Iwc9EFdIs9+AcxZIIpqto+sYcWbkGJ6CR0e6LYanQJH3d+Jcwh3q9CU27O7dp19Z7JXtgiiAO7qCmM80eHpep0V/QakXiv8RrebtqoyTrUD8Yz4rbqHZEFs5x/SOXLfGfcf4CZrl9ojmOtafrAN5sqnKY7zMAWAfLOP4IihmXbdYGiQ4Dv4sTIEKUo9Z72VeCyKZgO+LXU6LIWXY3Ww9OR3TsO5M+048Q2Sq4MEAojtQaS/dRnw4y9ct6KNn3D4z9pRANnhGC0vxvms710Hw2fpQBMAbw="
cache:
  yarn: true
  directories:
    - node_modules
script:
  - yarn lint
  - yarn build
deploy:
  - provider: script
    repo: konnectors/cozy-konnector-echeancier-maif
    skip-cleanup: true
    script: yarn deploy
    on:
      branch: master
  - provider: script
    repo: konnectors/cozy-konnector-echeancier-maif
    skip-cleanup: true
    script: DEPLOY_BRANCH=latest yarn deploy
    on:
      branch: prod
